db:
  db.options:
    driver: pdo_mysql
    host: localhost
    user:
    password:
    charset: utf8mb4

general:
  debug: true

twig:
  cachePath: appRoot:var/cache/
  styleSheets:
    - https://fonts.googleapis.com/css?family=Eczar:400,600,700,800|Work+Sans:400,400i
    - assets/css/screen.css
  templatePaths:
    - libraryRoot:templates/

server:
  serversPath:
  configsPath:
  errorLogPath:
  devDomainName: dev
  excludedServers:  []

routing:
  list:
    controller: \Hey\Controller\Index
    title: List
  build:
    controller: \Hey\Controller\Build
    title: Build
  db:
    controller: \Hey\Controller\Db
    title: Db
  error:
    controller: \Hey\Controller\Logs
    title: Logs
  info:
    controller: \Hey\Controller\Info
    title: Info